### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by minhvu120201dn** [yule-BUAA/DyGLib#10]
How do I infer the pretrained model? Thank you for reading and supporting me.

**Comment by yule-BUAA** [comment]
Hi,

You can run `evaluate_link_prediction.py` and `evaluate_node_classification.py` to do inference on the link prediction and node classification task, respectively.

Take the link prediction task as an example. Suppose that you have trained `DyGFormer` on `Wikipedia` dataset with its best configurations, then you can run
`python evaluate_link_prediction.py --dataset_name wikipedia --model_name DyGFormer --negative_sample_strategy random --load_best_configs --num_runs 1 --gpu 0`
to infer the trained model under random negative sampling strategy.

Infering on the node classification can also work in similar ways.
