### ISSUE TITLE
Questions about how to construt the initial <ml_network.csv> file for node classification task

### ISSUE THREAD

**Issue by mgao97** [yule-BUAA/DyGLib#13]
Hi,

I would like to inquire about the structure of the <ml_network.csv> file, which appears to be formatted with '“u,i,ts,label,idx' style. From my understanding, the "label" field represents the label associated with the source node.

However, I am considering the scenario where the graph is a directed and homogeneous graph. In such a case, would it be possible to include labels for the target nodes as well in the <ml_network.csv> file? These target nodes are also significant entities in our analysis.

Thank you for your response.

**Comment by yule-BUAA** [comment]
Hello,

If I understand correctly, a simple solution for the mentioned case is to add a new column (maybe named as `dst_label`) to the `<ml_network.csv>` file, which stores the label of target nodes.

Then, when loading the dataset for node classification, you can add a line below [here](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/utils/DataLoader.py#L212) to read the target node labels, like `dst_labels = graph_df.dst_label.values`. Also, remember to add a new property of `Data` at [here](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/utils/DataLoader.py#L48) and below [here](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/utils/DataLoader.py#L61), for example, `self.dst_labels = dst_labels`. Similarly, please get the target node labels [here](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/train_node_classification.py#L168) when using the target node labels to compute the loss.

**Comment by mgao97** [comment]
Thank you very much! I think it is clear to me now. 


I have another question regarding dynamic node classification. I have the edgelist csv file with three columns: source_id, target_id, and timestamp (a list of timestamps). the third column means that there are at least several interactions between the source node and the target node.
![image](https://github.com/yule-BUAA/DyGLib/assets/90015105/ba14921a-2a30-4de0-8ad1-d6edf4269ab3)

My question is that how to modify and condtruct the dataset and model trainig and test for supporting above scenario and dataset.

**Comment by yule-BUAA** [comment]
Firstly, for each line, you can split the interaction list into multiple lines, where each line stands for a single interaction. For example, split the first line `u18839785, u266463103, "['2022-01-14 xxxx', '2021-11-30 xxxx']"` into `u18839785, u266463103, '2022-01-14 xxxx'` and `u18839785, u266463103, '2021-11-30 xxxx'`.
Then, after splitting all the lines, you can sort the interactions in increasing order based on the timestamp.
The obtained data can be computed by our code.

**Comment by mgao97** [comment]
Thanks a lot! I will check it ASAP.

**Comment by yule-BUAA** [comment]
Close this issue now. Feel free to reopen it when needed.

**Comment by mgao97** [comment]
Hi,

I have a question regarding the dataset utilized in your code. Could you please specify if the dataset employed is an instance of a homogeneous graph within the context of dynamic node classification?

**Comment by yule-BUAA** [comment]
Hi,

Our work uses two datasets for dynamic node classification, including Wikipedia and Reddit. Compared with homogeneous graphs, these two datasets are bipartite with two types of nodes. You can refer to Section B.1 and Table 6 in our paper for more details.

**Comment by mgao97** [comment]
Yes, I see. 

However, I am uncertain as to how these models can be adapted to classify both source and target nodes in a single homogeneous graph. 

Wikipedia and Reddit both contain source nodes that are labelled, but in a homogeneous graph, both source and target nodes must be labelled.

 Could you please advise me on how to modify the code to accommodate this scenario? According to your previous suggestions https://github.com/yule-BUAA/DyGLib/issues/13#issuecomment-2080871203, it still does not work.

Thank you so much!

**Comment by yule-BUAA** [comment]
In my opinion, by adding a column to additionally denote the target node labels and loading them with slight code modifications, your case can be solved. Could you further explain why the previous suggestion cannot work?

**Comment by mgao97** [comment]
Sure!

One of the most important questions for me is how to construct the original csv file like wikipedia.csv? 

Specifically, I have 100 million edges and each with individual timestamp, I am not clear how to place the node features for both source nodes and target nodes in the original csv file. The node features are also about 1k dimensions.

**Comment by yule-BUAA** [comment]
We obtain the original files like `wikipedia.csv` from previous work [EdgeBank](https://arxiv.org/abs/2207.10128). 

For the mentioned case, you can directly place the edge features as the original `wikipedia.csv` does. Then, for node features, if the node features change over time, you can append the features of source and target nodes after edge feature at each line. Moreover, you should also record the edge and node feature dimensions, so that you can split them like [this](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/preprocess_data/preprocess_data.py#L39). If the node features are consistent regardless of time, you can additionally save node features in a separate file with shape (num_nodes, node_feat_dim), and then load the node features by the node index in each line.
