### ISSUE TITLE
TypeError:'float!object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by rabbityi1999** [yule-BUAA/DyGLib#7]
If you meet the problem: **TypeError:'float!object cannot be interpreted as an integer**, you could try to change "0.0" to "0" in DyGFormer.py (Line 372 and 378)

**Comment by yule-BUAA** [comment]
Hi,

This issue may be caused by the version of PyTorch you use. I use PyTorch `1.8.1` and it works fine for DyGFormer.
