### ISSUE TITLE
Questions about the application of the so-called Patching Technique

### ISSUE THREAD

**Issue by chengzhengyang** [yule-BUAA/DyGLib#8]
First of all, thank you for your outstanding work.

My question arose when I read this description in your paper

> Instead of focusing on the interaction level, we divide the encoding sequence into multiple non-overlapping patches to break through the bottleneck of existing methods in capturing long-term temporal dependencies.

Why should we divide the sequence into `num_patches * patch_size`'s? It doesn't seem to affect the long-term temporal dependencies that exist over an extended period of time within a sequence without doing this step?
Or
Have you experimentally proved that the results do improve with the help of this 'Patching Technique', i.e., that the staleness problem does occur during the training? I mean, Self-Attention Mechanism already allows processing whole sequence in parallel theoretically.

**Comment by yule-BUAA** [comment]
Hi, 

Thanks for your interest in our work!

The patching technique divides the original sequence into multiple patches to **reduce the input length of Transformer** whose computational complexity is quadratic to the input length. For example, suppose that the input sequence length is 200 and our patch size is 10. After patching, the input length is reduced to 200/10=20, which is much shorter than the original sequence length. Moreover, the patched sequence can also losslessly preserve the information in the original sequence. Thus, the patching technique enables our model to **access longer sequences with affordable computational costs**.

As shown in Figure 2 in our paper, our DyGFormer can compute on much longer sequences than most baselines with the patching technique. Also, Table 17 shows that the patching technique can effectively reduce computational costs and help DyGFormer deal with longer sequences.

**Comment by chengzhengyang** [comment]
Oh, ok, thanks.
Yes, the self-attention mechanism leads to a quadratic complexity in the number of tokens.

So this 'patching technique' is based on a perspective of computational consumption?
I didn't get that meaning from the quote literally, but It does make sense with respect to computational complexity.
