### ISSUE TITLE
time_interval_aware策略下计算采样概率为什么用的np.cumsum

### ISSUE THREAD

**Issue by guolalala** [yule-BUAA/DyGLib#9]
您好！请问一下 [此处](https://github.com/yule-BUAA/DyGLib/blob/3aacc36b94b8d2d8293d70a74fdf6d39089b4163/utils/utils.py#L124C59-L124C93) 代码中在`time_interval_aware`策略下计算采样的概率，为什么是除以 `np.cumsum(exp_node_neighbor_times)`，这样算出来的概率分布有什么特别的嘛？我试着输出了一下 `sampled_probabilities`，发现都是第一个是1，后续逐渐减小，似乎并没有特别的规律。
谢谢！

**Comment by yule-BUAA** [comment]
嗨，
这个采样的概率计算过程是对[CAWN](https://arxiv.org/pdf/2101.05974.pdf)中4.4章节 Efficient link sampling 中的采样方法的实现。其通过np.cumsum(exp_node_neighbor_times)累计计算的操作避免了对每个节点全部历史连边的列举，提升了采样效率。相关叙述和证明可以查看CAWN论文的附录A。我们的实现参考的是CAWN的[官方代码](https://github.com/snap-stanford/CAW/blob/f994ff2b2c29778e6250b6a9928fd9943e0163f7/graph.py#L70)。

**Comment by yule-BUAA** [comment]
我先关闭这个issue了哈。

如果后续有问题可以随时重启这个issue。
